[colors.bright]
black = "#000000"
blue = "#338fff"
cyan = "#9ac8e0"
green = "#44df44"
magenta = "#ff66ff"
red = "#ff5f5f"
white = "#ffffff"
yellow = "#efef00"

[colors.dim]
black = "#000000"
blue = "#82b0ec"
cyan = "#9ac8e0"
green = "#88ca9f"
magenta = "#caa6df"
red = "#ff9580"
white = "#989898"
yellow = "#d2b580"

[colors.normal]
black = "#000000"
blue = "#2fafff"
cyan = "#00d3d0"
green = "#44bc44"
magenta = "#feacd0"
red = "#ff5f59"
white = "#ffffff"
yellow = "#d0bc00"

[colors.primary]
background = "#000000"
bright_foreground = "#ffffff"
dim_foreground = "#1e1e1e"
foreground = "#ffffff"
