# "window.opacity" = 0.4

[colors.bright]
black = "#000000"
blue = "#387CD3"
cyan = "#3D97E2"
green = "#00FF7F"
magenta = "#957BBE"
red = "#FF0000"
white = "#FFFFFF"
yellow = "#EFD64B"

[colors.normal]
black = "#000000"
blue = "#1C98E8"
cyan = "#80CDCD"
green = "#00FF7F"
magenta = "#FF00FF"
red = "#FF0000"
white = "#FFFFFF"
yellow = "#F2D42C"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[cursor]
style = "Beam"

[font]
size = 11

[font.bold]
family = "Envy Code R"
style = "Bold"

[font.bold_italic]
family = "Envy Code R"
style = "Bold Italic"

[font.italic]
family = "Envy Code R"
style = "Italic"

[font.normal]
family = "Envy Code R"
style = "Regular"

[general]
import = ["/home/fade/.config/alacritty/Alacritty-modus-themes/modus-vivendi.toml"]
